-- Portfolio core schema.
-- Enum-like columns use text + CHECK rather than native PG enums: Hibernate maps them
-- cleanly, and adding a value later is a one-line constraint change instead of a type
-- migration.

create table public.projects (
  id             bigint generated by default as identity primary key,
  slug           text        not null unique,
  title          text        not null,
  tagline        text,
  description    text,
  domain         text        not null
                 check (domain in ('AI','SECURITY','GRAPHICS','SYSTEMS','ML','WEB')),
  stack          text[]      not null default '{}',
  live_url       text,
  repo_url       text,
  writeup_url    text,
  poster_url     text,
  backdrop_url   text,
  trailer_url    text,
  status         text        not null default 'WIP'
                 check (status in ('LIVE','WIP','ARCHIVED')),
  featured       boolean     not null default false,
  complexity     smallint    not null default 2 check (complexity between 1 and 3),
  released_at    date,
  trending_score numeric(10,4) not null default 0,
  sort_order     integer     not null default 0,
  created_at     timestamptz not null default now(),
  updated_at     timestamptz not null default now()
);

comment on column public.projects.complexity is '1..3, rendered as an SDE-1/2/3 badge';
comment on column public.projects.trending_score is 'Recomputed nightly; never written by clients';

create index projects_domain_idx   on public.projects (domain);
create index projects_status_idx   on public.projects (status);
create index projects_trending_idx on public.projects (trending_score desc);
create index projects_released_idx on public.projects (released_at desc nulls last);

create table public.project_events (
  id           bigint generated by default as identity primary key,
  project_id   bigint      not null references public.projects (id) on delete cascade,
  event_type   text        not null
               check (event_type in ('VIEW','OPEN','CLICK_LIVE','CLICK_REPO')),
  session_hash text,   -- salted hash only; raw IPs are never stored
  referrer     text,
  occurred_at  timestamptz not null default now()
);

create index project_events_project_time_idx on public.project_events (project_id, occurred_at desc);
create index project_events_time_idx         on public.project_events (occurred_at desc);

create table public.project_daily_stats (
  project_id bigint  not null references public.projects (id) on delete cascade,
  day        date    not null,
  views      integer not null default 0,
  opens      integer not null default 0,
  clicks     integer not null default 0,
  primary key (project_id, day)
);

create table public.skills (
  id          bigint generated by default as identity primary key,
  name        text     not null unique,
  category    text     not null
              check (category in ('LANGUAGE','FRAMEWORK','DATA','DEVOPS','AI','MOBILE','TOOLING')),
  proficiency smallint not null default 3 check (proficiency between 1 and 5),
  favorite    boolean  not null default false,
  icon_slug   text,
  years_used  numeric(3,1),
  sort_order  integer  not null default 0,
  created_at  timestamptz not null default now()
);

create index skills_favorite_idx on public.skills (favorite desc, sort_order);

create table public.certifications (
  id             bigint generated by default as identity primary key,
  name           text not null,
  issuer         text not null,
  issued_on      date,
  expires_on     date,
  credential_id  text,
  credential_url text,
  badge_url      text,
  sort_order     integer not null default 0,
  created_at     timestamptz not null default now()
);

create table public.blog_posts (
  id              bigint generated by default as identity primary key,
  slug            text not null unique,
  title           text not null,
  excerpt         text,
  content_md      text,
  cover_url       text,
  tags            text[] not null default '{}',
  status          text not null default 'DRAFT' check (status in ('DRAFT','PUBLISHED')),
  reading_minutes smallint,
  published_at    timestamptz,
  created_at      timestamptz not null default now(),
  updated_at      timestamptz not null default now()
);

create index blog_published_idx on public.blog_posts (status, published_at desc);

create table public.profile (
  id         bigint generated by default as identity primary key,
  singleton  boolean not null default true,
  name       text not null,
  headline   text,
  bio        text,
  email      text,
  location   text,
  resume_url text,
  socials    jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now()
);

create unique index profile_singleton_idx on public.profile ((singleton)) where singleton;

create table public.contact_messages (
  id           bigint generated by default as identity primary key,
  name         text not null,
  email        text not null,
  message      text not null,
  session_hash text,
  handled      boolean not null default false,
  created_at   timestamptz not null default now()
);

create index contact_created_idx on public.contact_messages (created_at desc);

create or replace function public.touch_updated_at()
returns trigger language plpgsql security definer set search_path = '' as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create trigger projects_touch before update on public.projects
  for each row execute function public.touch_updated_at();
create trigger blog_touch     before update on public.blog_posts
  for each row execute function public.touch_updated_at();
create trigger profile_touch  before update on public.profile
  for each row execute function public.touch_updated_at();
