-- Seed data: 18 projects carried over from the previous portfolio build.
-- Generated from src/data/projects.ts. Dates are git first-commit or directory mtime.
-- Idempotent: re-running updates rather than duplicating.

INSERT INTO projects
  (slug, title, tagline, description, domain, stack, live_url, repo_url, writeup_url,
   status, featured, complexity, released_at)
VALUES
  ('contractcal', 'ContractCal', 'Self-hosted contract obligation tracking.', 'Self-hosted contract obligation tracking. Retrieval-augmented extraction pulls deadlines, renewals and liability dates out of contract text so a missed clause stops being a filing problem.', 'AI', ARRAY['RAG','Supabase','Docker','TypeScript']::text[], 'https://contract-cal.vercel.app', NULL, NULL, 'LIVE', false, 2, '2026-08-10'),
  ('dentos', 'DentOS', 'A clinical operating system for dental practice.', 'A clinical operating system for dental practice. Twenty-seven modules in one deployable, where module boundaries are enforced by the compiler — the build fails before a reviewer has to catch a violation.', 'SYSTEMS', ARRAY['Java 21','Spring Boot','Angular','PostgreSQL']::text[], 'https://dentistree.vercel.app', 'https://github.com/XSoloLevelerX/dentos', NULL, 'LIVE', true, 3, '2026-08-04'),
  ('envforge', 'EnvForge', 'Prompt to game-ready 3D environment in the browser.', 'Prompt to game-ready 3D environment in the browser. Twelve hand-built procedural modules, rules-driven scatter placement across three scale tiers, and a GLB export a game engine will actually accept.', 'GRAPHICS', ARRAY['React Three Fiber','Three.js','Zustand','TypeScript']::text[], NULL, NULL, NULL, 'WIP', true, 3, '2026-08-03'),
  ('saveyourlivestock', 'SaveYourLivestock', 'Real-time livestock intrusion detection on ordinary security cameras.', 'Real-time livestock intrusion detection on ordinary security cameras. A motion filter gates YOLOv8 so the classifier only runs when something moved, which is what makes it viable on farm hardware.', 'ML', ARRAY['Python','YOLOv8','OpenCV','Flask']::text[], NULL, NULL, NULL, 'WIP', true, 2, '2026-08-02'),
  ('safemap', 'SafeMap', 'Safety-aware routing across four surfaces — Flutter app, Kotlin client, web UI and a microservice backend — sharing one incident dataset and one scoring model.', 'Safety-aware routing across four surfaces — Flutter app, Kotlin client, web UI and a microservice backend — sharing one incident dataset and one scoring model.', 'SYSTEMS', ARRAY['Flutter','Kotlin','Microservices','Supabase']::text[], NULL, NULL, NULL, 'WIP', false, 3, '2026-08-01'),
  ('grand-luxury', 'Grand Luxury', 'An AI concierge platform for hotels.', 'An AI concierge platform for hotels. Guests talk to an LLM that raises real service requests, staff pick the work up on mobile, and managers watch the whole queue move on a web dashboard.', 'AI', ARRAY['Python','LLM','React Native','Postgres']::text[], NULL, 'https://github.com/XSoloLevelerX/Call-Voice-Agent', NULL, 'WIP', false, 3, '2026-07-31'),
  ('glyphguard', 'GlyphGuard', 'A trust proxy for the Model Context Protocol.', 'A trust proxy for the Model Context Protocol. It reads every tool description before the model does and quarantines the ones carrying hidden instructions, closing a prompt-injection path most MCP users never see.', 'SECURITY', ARRAY['Python','MCP','Docker']::text[], 'https://glyphguard.vercel.app', 'https://github.com/XSoloLevelerX/GlyphGuard---MCP-Tool-Poisoning-Trust-Proxy', NULL, 'LIVE', true, 3, '2026-07-30'),
  ('excelflow', 'ExcelFlow', 'A browser-based cleanup tool for people who find Excel formulas painful — twelve-plus filter operators with AND/OR composition, running entirely client-side so nothing ever leaves the browser.', 'A browser-based cleanup tool for people who find Excel formulas painful — twelve-plus filter operators with AND/OR composition, running entirely client-side so nothing ever leaves the browser.', 'SYSTEMS', ARRAY['FastAPI','Python','JavaScript','Docker']::text[], NULL, NULL, NULL, 'WIP', false, 1, '2026-07-16'),
  ('vms', 'VMS', 'A visitor management system for multi-site operations — OTP and OAuth2 login, role-scoped access across admin, security, and warehouse roles, and a Flutter client talking to one Spring Boot API.', 'A visitor management system for multi-site operations — OTP and OAuth2 login, role-scoped access across admin, security, and warehouse roles, and a Flutter client talking to one Spring Boot API.', 'SYSTEMS', ARRAY['Spring Boot','Flutter','JWT / OAuth2']::text[], NULL, NULL, NULL, 'WIP', false, 2, '2026-07-16'),
  ('meccha', 'MECCHA CHAMELEON', 'A browser game built on a BVH-accelerated Three.', 'A browser game built on a BVH-accelerated Three.js scene, with Supabase-backed state and Playwright driving the gameplay regression suite.', 'GRAPHICS', ARRAY['Three.js','three-mesh-bvh','React','Supabase']::text[], 'https://meccha-chameleon-beta.vercel.app', 'https://github.com/XSoloLevelerX/MECCHA-CHAMELEON', NULL, 'LIVE', false, 2, '2026-07-05'),
  ('hermes', 'Hermes', 'A self-hosted coding agent that persists your identity across sessions.', 'A self-hosted coding agent that persists your identity across sessions. Personality, principles and coding style live in versioned files, so the agent stays recognisably yours instead of resetting each run.', 'AI', ARRAY['Python','Ollama','Claude','RAG']::text[], NULL, NULL, NULL, 'WIP', true, 2, '2026-05-14'),
  ('pitlane', 'PitLane AI', 'An F1 intelligence platform built on the APEX engine: live telemetry, cross-era statistical comparison, and 3D circuit visualisation behind an LLM race engineer that argues strategy with you.', 'An F1 intelligence platform built on the APEX engine: live telemetry, cross-era statistical comparison, and 3D circuit visualisation behind an LLM race engineer that argues strategy with you.', 'AI', ARRAY['Next.js','Three.js','Anthropic','Supabase']::text[], NULL, 'https://github.com/XSoloLevelerX/PitLaneAI', NULL, 'WIP', true, 3, '2026-05-03'),
  ('tokenlens', 'Token Lens', 'A VS Code extension that tracks LLM token spend per session, right where the tokens get spent — a webview dashboard instead of a bill you only see at the end of the month.', 'A VS Code extension that tracks LLM token spend per session, right where the tokens get spent — a webview dashboard instead of a bill you only see at the end of the month.', 'AI', ARRAY['TypeScript','VS Code API','esbuild']::text[], NULL, NULL, NULL, 'WIP', false, 1, '2026-03-25'),
  ('docparser', 'DocParser', 'Template-driven document extraction: define the fields once, then pull structured data out of scanned or digital documents via Tesseract OCR without hand-rolling a parser per document type.', 'Template-driven document extraction: define the fields once, then pull structured data out of scanned or digital documents via Tesseract OCR without hand-rolling a parser per document type.', 'ML', ARRAY['Next.js','Tesseract.js','Express']::text[], NULL, NULL, NULL, 'WIP', false, 2, '2026-02-26'),
  ('hotel-management', 'Hotel Management System', 'Full-stack property management with a shared type layer between frontend and backend, Supabase persistence, and Playwright end-to-end coverage over the booking flow.', 'Full-stack property management with a shared type layer between frontend and backend, Supabase persistence, and Playwright end-to-end coverage over the booking flow.', 'SYSTEMS', ARRAY['TypeScript','Supabase','Playwright']::text[], NULL, 'https://github.com/XSoloLevelerX/Hotel_Management_System', NULL, 'WIP', false, 2, '2026-02-20'),
  ('indian-stock-sidebar', 'Indian Stock Sidebar', 'A Manifest V3 Chrome extension that turns any tab into an NSE ticker — alarm-driven refresh, a badge that changes color with the stock, no dashboard tab required.', 'A Manifest V3 Chrome extension that turns any tab into an NSE ticker — alarm-driven refresh, a badge that changes color with the stock, no dashboard tab required.', 'SYSTEMS', ARRAY['Chrome Extension','JavaScript','Manifest V3']::text[], NULL, NULL, NULL, 'WIP', false, 1, '2026-02-19'),
  ('indifolio', 'IndiFolio Pro', 'An investment portfolio tracker that pairs live yfinance market data with a Gemini-driven ''Deep Search'' for equity research, so the numbers and the narrative sit in one place.', 'An investment portfolio tracker that pairs live yfinance market data with a Gemini-driven ''Deep Search'' for equity research, so the numbers and the narrative sit in one place.', 'AI', ARRAY['FastAPI','Next.js','yfinance','Gemini']::text[], NULL, NULL, NULL, 'WIP', false, 2, '2026-02-12'),
  ('vibematch', 'VibeMatch AI', 'Music discovery by emotional arc rather than genre.', 'Music discovery by emotional arc rather than genre. An eight-stage pipeline models how a track evolves over time, then matches songs whose structure rises and falls the same way.', 'ML', ARRAY['Python','ML','Audio DSP']::text[], NULL, NULL, NULL, 'WIP', false, 2, '2026-01-26')
ON CONFLICT (slug) DO UPDATE SET
  title = EXCLUDED.title, tagline = EXCLUDED.tagline, description = EXCLUDED.description,
  domain = EXCLUDED.domain, stack = EXCLUDED.stack, live_url = EXCLUDED.live_url,
  repo_url = EXCLUDED.repo_url, status = EXCLUDED.status, featured = EXCLUDED.featured,
  complexity = EXCLUDED.complexity, released_at = EXCLUDED.released_at,
  updated_at = now();
